title: Houda Khaled
description: Houda Khaled's personal site

url: http://houdak.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
- title: CV
   url: /CV

social:
   email: hkhaled@jhu.edu
   github: houdak
   twitter: 
   facebook:
   linkedin: https://www.linkedin.com/in/houda-khaled/

google_analytics: # Tracking ID, e.g. "UA-000000-01"
